version: '3.9'

services:
  api:
    build:
      context: ./services/api
    env_file:
      - ./.env
    command: bash -lc "python manage.py makemigrations && python manage.py migrate && gunicorn univote.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - app-net

  anomaly:
    build:
      context: ./services/anomaly
    env_file:
      - ./.env
    command: uvicorn app:app --host 0.0.0.0 --port 8100
    ports:
      - "8100:8100"
    networks:
      - app-net

  web:
    build:
      context: ./services/web
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-net

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: univote
      POSTGRES_USER: univote
      POSTGRES_PASSWORD: univote
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - app-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  pgdata:
  mongodata:

